/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useCallback } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { useWheel } from './store'
import Screen from './Screen'
import { useTweaks } from 'use-tweaks'

function Cylinder({ i, ...props }) {
  const paletteIndex = useWheel(state => state.colors[i])
  const setIndex = useWheel(state => state.setIndex)
  const handleClick = useCallback( (e) => { 
    e.stopPropagation() 
    setIndex(i, (paletteIndex + 1) % 5)
  }, [paletteIndex] )

  const palette = useWheel((s) => s.palette)

  return (
    <mesh castShadow receiveShadow onClick={handleClick} {...props}>
      <meshStandardMaterial metalness={0.9} roughness={1} color={palette[paletteIndex]} />
    </mesh>
  )
}

export default function Model(props) {
  const { nodes } = useGLTF('/Color3.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.54, 1.08, 1.69]}>
        {new Array(36).fill().map((_, index) => (
          <Cylinder
            key={`0${index}`}
            i={index}
            rotation={[0, -Math.PI / 2, -Math.PI / 2]}
            geometry={nodes[`Cylinder${index === 0 ? '' : index < 10 ? `00${index}` : `0${index}`}`].geometry}
          />
        ))}
      </group>
      <Screen />
      <mesh castShadow geometry={nodes.Cube.geometry} position={[0, 1, 0]} rotation-x={Math.PI / 2}>
        <meshStandardMaterial metalness={0.39} roughness={0.41} color="#555555" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Color.gltf')
