/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/colors.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.54, 1.08, 1.69]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['Material.037']} geometry={nodes.Cylinder.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.002']} geometry={nodes.Cylinder001.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.003']} geometry={nodes.Cylinder002.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.004']} geometry={nodes.Cylinder003.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.005']} geometry={nodes.Cylinder004.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.006']} geometry={nodes.Cylinder005.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.007']} geometry={nodes.Cylinder006.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.008']} geometry={nodes.Cylinder007.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.009']} geometry={nodes.Cylinder008.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.010']} geometry={nodes.Cylinder009.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.011']} geometry={nodes.Cylinder010.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.012']} geometry={nodes.Cylinder011.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.013']} geometry={nodes.Cylinder012.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.014']} geometry={nodes.Cylinder013.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.015']} geometry={nodes.Cylinder014.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.016']} geometry={nodes.Cylinder015.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.017']} geometry={nodes.Cylinder016.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.018']} geometry={nodes.Cylinder017.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.019']} geometry={nodes.Cylinder018.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.020']} geometry={nodes.Cylinder019.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.021']} geometry={nodes.Cylinder020.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.022']} geometry={nodes.Cylinder021.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.023']} geometry={nodes.Cylinder022.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.024']} geometry={nodes.Cylinder023.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.025']} geometry={nodes.Cylinder024.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.026']} geometry={nodes.Cylinder025.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.027']} geometry={nodes.Cylinder026.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.028']} geometry={nodes.Cylinder027.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.029']} geometry={nodes.Cylinder028.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.030']} geometry={nodes.Cylinder029.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.031']} geometry={nodes.Cylinder030.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.032']} geometry={nodes.Cylinder031.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.033']} geometry={nodes.Cylinder032.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.034']} geometry={nodes.Cylinder033.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.035']} geometry={nodes.Cylinder034.geometry} rotation={[0, -1.57, 0]} />
        <mesh material={materials['Material.036']} geometry={nodes.Cylinder035.geometry} rotation={[0, -1.57, 0]} />
      </group>
      <mesh
        material={materials.black}
        geometry={nodes.Cube.geometry}
        position={[0, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials.sc} geometry={nodes.Slice.geometry} />
      </mesh>
      <mesh material={materials['Plane-mat']} geometry={nodes.Plane.geometry} />
    </group>
  )
}

useGLTF.preload('/colors.glb')
